### ISSUE TITLE
present exception when I go to Customers ->Pending Customers

### ISSUE THREAD

**Issue by alessandroscalesse** [halexm2/customer-approval#1]
![Screenshot 2024-03-15 122219](https://github.com/halexm2/customer-approval/assets/144102031/f81b7b92-117e-4401-9c71-4df3a720aaf7)

![image](https://github.com/halexm2/customer-approval/assets/144102031/1f4af616-c53e-4249-9d65-0c0fd1c00b42)

**Comment by alessandroscalesse** [comment]
Magento ver. 2.4.6-p3

**Comment by halexm2** [comment]
Thank you, I'm checking
